# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-28 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigation',
            options={'verbose_name': '导航', 'verbose_name_plural': '导航'},
        ),
        migrations.AlterField(
            model_name='navigation',
            name='nav_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='nav_name',
            field=models.CharField(max_length=64, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='shopimage',
            name='shop_img_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(upload_to='upload/img/%Y%m%d', verbose_name='头像'),
        ),
    ]
